Vendas/Models/CarrinhoCompraItem.cs
using System.ComponentModel.DataAnnotations;

namespace Vendas.Models
{
    
    public class CarrinhoCompraItem
    {
        public int CarrinhoCompraItemId { get; set; }
        public Lanche Lanche { get; set; }
        public int Quantidade { get; set; }
        [StringLength(200)]
        public string CarrinhoCompraId { get; set; }
    }
}

Vendas/Models/Categoria.cs
using System.ComponentModel.DataAnnotations;

namespace Vendas.Models
{
    public class Categoria
    {
        [Key]
        public int CategoriaId { get; set; }
        [StringLength(100,ErrorMessage="O tamanho máximo é 100 caracteres")]
        [Required(ErrorMessage ="Informe o nome da categoria")]
        [Display(Name = "Nome")]
        public string CategoriaNome { get; set; }
        [StringLength(200, ErrorMessage = "O tamanho máximo é 200 caracteres")]
        [Required(ErrorMessage = "Informe a descrição da categoria")]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }

        //Relacionamento de Categoria para Lanche (uma categoria tem muitos lanches)
        public List<Lanche> Lanches { get; set; }

    }
}

Vendas/Models/ErrorViewModel.cs
namespace Vendas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Vendas/Models/Lanche.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Vendas.Models
{    
    public class Lanche
    {
        [Key]        
        public int LancheId { get; set; }
        [StringLength(80,MinimumLength =10, ErrorMessage = "O tamanho máximo é 80 caracteres")]
        [Required(ErrorMessage = "Informe o nome do lanche deve ser informado")]
        [Display(Name = "Nome do Lanche")]
        public string Nome { get; set; }
        [StringLength(200, MinimumLength = 10, ErrorMessage = "minimo de 10 maximo de 200")]
        [Required(ErrorMessage = "Descrição deve ter no mínimo 10 caracteres")]
        [Display(Name = "Descrição do Lanche")]
        public string DescricaoCurta { get; set; }
        [StringLength(200, MinimumLength = 20, ErrorMessage = "minimo de 20 maximo de 200")]
        [Required(ErrorMessage = "Descrição deve ter no mínimo 20 caracteres")]
        [Display(Name = "Descrição detalhada do Lanche")]
        public string DescricaoDetalhada { get; set; }
        [Required(ErrorMessage = "Informe o preço")]
        [Display(Name = "Preço")]
        [Column(TypeName ="decimal(10,2)")]
        [Range(1,999.99,ErrorMessage ="Preço deve estar entre 1 e 999,99")]
        public decimal Preco { get; set; }
        [StringLength(200, ErrorMessage = "maximo de 200 caract")]       
        [Display(Name = "Caminho imagem")]
        public string ImagemUrl { get; set; }
        [StringLength(200, ErrorMessage = "maximo de 200 caract")]
        [Display(Name = "Caminho imagem miniatura")]
        public string ImagemThumbnailUrl { get; set; }
        [Display(Name = "Preferido?")]
        public bool IsLanchePreferido { get; set; }
        [Display(Name = "Em estoque?")]
        public bool EmEstoque { get; set; }

        //Relacionamento de Lanche para Categoria
        public int CategoriaId { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}

Vendas/ViewModels/LancheListViewModel.cs
using Vendas.Models;

namespace Vendas.ViewModels
{
    public class LancheListViewModel
    {
        public IEnumerable<Lanche> Lanches { get; set; }
        public string CategoriaAtual { get; set; }
    }
}

Vendas/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Vendas.Models;

namespace Vendas.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Vendas/Controllers/LancheController.cs
using Microsoft.AspNetCore.Mvc;
using Vendas.Repositories.Interfaces;
using Vendas.ViewModels;

namespace Vendas.Controllers
{
    public class LancheController : Controller
    {
        public readonly ILancheRepository _lancheRepository;
        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult List()
        {
            //var lanches = _lancheRepository.Lanches;
            //return View(lanches);
            var lanchesListViewModel = new LancheListViewModel();
            lanchesListViewModel.Lanches = _lancheRepository.Lanches;
            lanchesListViewModel.CategoriaAtual = "Categoria Atual";

            return View(lanchesListViewModel);

        }
    }
}

Vendas/Views/Home/Index.cshtml
<h1>View Model</h1>
<partial name="_Carousel"/>

Vendas/Views/Lanche/List.cshtml
@model LancheListViewModel

    <div><h2>@Model.CategoriaAtual</h2></div>

   <div class="container">
       <div class="row">
    @foreach(var lanche in Model.Lanches)
    {
        <partial name ="_LanchesResumo" for ="@lanche"/>
    }
       </div>
    </div>

Vendas/Views/Shared/_Carousel.cshtml
<div id="carouselLanches" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="~/images/carousel1.jpg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="~/images/carousel11.jpg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="~/images/carousel12.jpg" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="~/images/carousel13.jpg" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="~/images/carousel14.jpg alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="~/images/carousel2.jpg" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="~/images/carousel3.jpg" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="~/images/carousel4.jpg" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="~/images/carousel5.jpg" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselLanches" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselLanches" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

Vendas/Views/Shared/_LanchesResumo.cshtml
@model Lanche

<div class="com-sm-4 col-md-4 col-lg-4">
         <p><img src="@Model.ImagemUrl" class="img-fluid"/></p>
         <h3>@Model.Preco.ToString("c")</h3>
         <h4>@Model.Nome</h4>
         <p>@Model.DescricaoCurta</p>         
</div>

Vendas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vendas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Vendas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vendas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>           
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lanche" asp-action="List">Lanches</a>
                        </li>  
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Vendas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>